### ISSUE TITLE
Slash commands update might have broken my bot

### ISSUE THREAD

**Issue by dkhelpling** [discord/discord-interactions-js#14]
https://canary.discord.com/channels/613425648685547541/697138785317814292/832859421952180245

Slash Commands Update (Midnight Snack Edition)

We have released a change to HTTP interactions which modifies how responses are handled. Due in part to this, you should ensure you respond to HTTP interactions with a valid Content-Type header. Interactions received via the gateway (INTERACTION_CREATE events) are unaffected by this change.

My bot was working fine through AWS lambda using this package until recently. Have there been any issues around this update?

**Comment by typpo** [comment]
If this update affected your bot, you may need to set the `Content-Type` header to `application/json` in your Lambda response
