### ISSUE TITLE
'arrayBuffer' is declared but its value is never read.

### ISSUE THREAD

**Issue by katopz** [discord/discord-interactions-js#24]
Refer to
https://github.com/discord/discord-interactions-js/blob/main/src/index.ts#L96-L97

```ts
      const arrayBuffer = value.buffer.slice(value.byteOffset, value.byteOffset + value.length);
      return new Uint8Array(value);
```
ts warning...
```
'arrayBuffer' is declared but its value is never read.
```

So the question is `arrayBuffer` didn't use when return, is this a bug or intend?

**Comment by typpo** [comment]
Looks like it is unused, and therefore should be removed

**Comment by JustinBeckwith** [comment]
Fairly sure this was addressed :)
