### ISSUE TITLE
discord-interactions throws error 'Invalid signature'

### ISSUE THREAD

**Issue by unrealv1** [discord/discord-interactions-js#26]
When I send a POST request I get this error: `[discord-interactions] Invalid signature`
This is what I get on the console: `[discord-interactions]: Invalid verifyKey parameters Error: Value is not a valid hex string`

Here's the code:
```js
const express = require('express');
const { InteractionType, InteractionResponseType, verifyKeyMiddleware } = require('discord-interactions');

const app = express();

app.post('/interactions', verifyKeyMiddleware('client-public-key-here'), (req, res) => {
  const interaction = req.body;
  if (interaction.type === InteractionType.APPLICATION_COMMAND) {
    res.send({
      type: InteractionResponseType.CHANNEL_MESSAGE_WITH_SOURCE,
      data: {
        content: 'Hello world',
      },
    });
}
```

**Comment by Taimoor-Tariq** [comment]
Are you using your discord bot token or the public key?
You are suppose to use the public key

**Comment by unreal189** [comment]
> Are you using your discord bot token or the public key? You are supposed to use the public key

Yes, I'm using my client public key.
