### ISSUE TITLE
How does discord use win getProcess function in javascript?

### ISSUE THREAD

**Issue by ninetynin** [discord/discord-interactions-js#36]
This is a personal doubt question and not a issue in this repo ig... 
I'm asking here because this repo seemed a correct place to ask about it..

Incase anyone ever noticed when u have a discord application installed and you use discord web it prompts u to open in discord app so most prolly its using getprocess win library function 
Does anyone mnd sharing how that's done in javascript or typescript ... I cant find any stuff related to that 😭

Thanks

**Comment by akirataguchi115** [comment]
Could you give an example of an installable Discord application?

**Comment by JustinBeckwith** [comment]
Greetings!  This is kind of off topic, and you may get a better answer over in our Discord Developers Server - https://discord.com/invite/discord-developers
