### ISSUE TITLE
MessageEmbed .addFields No Longer Supports User Mentions

### ISSUE THREAD

**Issue by RC-Projects** [discord/discord-interactions-js#47]
When using `MessageEmbed.addField` users can be mentioned without any issue in a embedded message.

EG:

`var.addField{ name:  From: <@${feedbackFound.user_id}>}` correctly displays `@UserName`

Where as:

`var.addFields{ name:  From: <@${feedbackFound.user_id}>}` instead displays `<@123456789>`

Is this intended? Does the new `.addFields` intentially not support user mentions?

**Comment by IanMitchell** [comment]
You'll want the discord.js repo, not this one! But generally that's a Discord client side cache thing - if the user isn't in your cache it will appear that way, whereas if it's a user you've loaded it will render their name.

**Comment by RC-Projects** [comment]
> You'll want the discord.js repo, not this one! But generally that's a Discord client side cache thing - if the user isn't in your cache it will appear that way, whereas if it's a user you've loaded it will render their name.

Thanks! I saw an issue on the discord.js repo that was somewhat similar where the recommendation was to coed to the discord repos instead. I'll look more into getting these items cached.

I appreciate your help!
