### ISSUE TITLE
Replace `tweetnacl` with `discord-verify`

### ISSUE THREAD

**Issue by IanMitchell** [discord/discord-interactions-js#54]
The tweetnacl library has a massive impact on bot performance due to its usage of non-native code. [`discord-verify`](https://www.npmjs.com/package/discord-verify) uses new native methods for verification that results in a dramatic performance increase.

This was the real world performance benefits the Truth or Dare bot saw when they swapped off of `discord-interactions` and deployed `discord-verify`:

![image](https://github.com/discord/discord-interactions-js/assets/603872/cc75c359-b88b-4ddc-b053-a8d464e81a79)

The library also protects against additional security concerns such as replay attacks.

**Comment by jb3** [comment]
Switching from TweetNaCl to Discord-Verify has been a game-changer for me. Thanks to Ian Mitchell's brilliant library, I've slashed CPU wall time, giving me the freedom to prioritize what truly matters in life. With the efficiency gains, I've been able to cherish precious moments with my wife, embark on the journey of starting a family, and achieve the dream of buying our first house.

Ian Mitchell's contribution to this shift cannot be overstated. His dedication to crafting an optimized and reliable library like Discord-Verify has not only improved my workflow but has also enriched my personal life beyond measure. Grateful doesn't begin to describe how I feel about the impact of his work. Here's to Ian Mitchell and the power of technology to enhance our lives in unexpected ways. Cheers to efficiency, family, and dreams realized!

**Comment by advaith1** [comment]
yes tweetnacl slow native fast pls fix

https://x.com/advaithj1/status/1420696472933175297
![image](https://github.com/discord/discord-interactions-js/assets/11778454/afaa04fe-61a6-4856-9723-bc5b8b9a4f99)

**Comment by thewilloftheshadow** [comment]
Absolutely agree with whats been stated here, switching from discord-interactions to discord-verify dropped execution time dramatically for my workers

**Comment by typpo** [comment]
IDK, I switched to discord-verify and it increased my execution time

![](https://github.com/discord/discord-interactions-js/assets/310310/6c208fd2-8d79-498f-92e1-b5e0936f4a2c)
