### ISSUE TITLE
verifyKeyMiddleware used in conjunction with bodyParser stops requests from getting to the callback

### ISSUE THREAD

**Issue by Yamboy1** [discord/discord-interactions-js#6]
When using both verifyKeyMiddleware and bodyParser.json() (in any order) together, my app.post callback doesn't run, however if i comment out one of the app.use lines, it works:
```js
const express = require("express");
const bodyParser = require("body-parser");
const { InteractionResponseType, InteractionType, verifyKeyMiddleware } = require("discord-interactions");

const config = require("./config.json");

const app = express();
const port = 3000;

app.use(verifyKeyMiddleware(config.publicKey));
app.use(bodyParser.json());

app.post("/", (req, res) => {
  console.log("here");
  const message = req.body;
  console.log(message.type);
  if (message.type === InteractionType.COMMAND) {
    res.send({
      type: InteractionResponseType.CHANNEL_MESSAGE_WITH_SOURCE,
      data: {
        content: 'Hello world',
      }
    });
  } else {
    res.send({})
  }
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
```

**Comment by Yamboy1** [comment]
bodyParser debug logs when verifyKeyMiddleware is used:
![image](https://user-images.githubusercontent.com/37413895/102043172-92fbd380-3e38-11eb-97e3-6f37e9892b5d.png)

bodyParser debug logs when verifyKeyMIddleware is commented out:
![image](https://user-images.githubusercontent.com/37413895/102043222-b1fa6580-3e38-11eb-9dae-51d298fde592.png)

**Comment by LewisTehMinerz** [comment]
What version of the library was this?

**Comment by typpo** [comment]
Yeah, they are both trying to read the raw request, and when the second one runs there is no more raw request to read.  I'll have a fix for this later today.

**Comment by typpo** [comment]
Improved in 1.3.1.  Middleware will handle body parsing for you so you don't need bodyparser, you can just use `req.body` directly.  If you must use bodyparser in your project for other routes, be sure to only apply bodyparser to those routes (e.g. [express_app_with_bodyparser.js](https://github.com/discord/discord-interactions-js/blob/main/examples/express_app_with_bodyparser.js))

The middleware will try to handle things if bodyparser has already modified the request, but will emit a warning.
