### ISSUE TITLE
Switch signature verification to tweetnacl

### ISSUE THREAD

**Issue by typpo** [discord/discord-interactions-js#8]
Switch from noble-ed25519 to [tweetnacl](https://www.npmjs.com/package/tweetnacl).  It's a more popular library that has been audited.

**Comment by pizzafox** [comment]
The [Discord.js](https://discord.js.org) PR to implement Interactions https://github.com/discordjs/discord.js/pull/5106 is using tweetnacl, perhaps their code can be of use?

See: https://github.com/discordjs/discord.js/pull/5106/files#diff-e829131a6f4c04ecfc7a3f7f01468bedefbee5e19441c8d9bbc08d852da7d8d6R168-R189
